CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Academias" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    CONSTRAINT "PK_Academias" PRIMARY KEY ("Id")
);

CREATE TABLE "Procesos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Anio" integer NOT NULL,
    "Periodo" text NOT NULL,
    "FechaInicio" timestamp with time zone NOT NULL,
    "FechaFin" timestamp with time zone NOT NULL,
    "Activo" boolean NOT NULL,
    CONSTRAINT "PK_Procesos" PRIMARY KEY ("Id")
);

CREATE TABLE "Instrumentos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "AcademiaId" integer NOT NULL,
    "Activo" boolean NOT NULL,
    CONSTRAINT "PK_Instrumentos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Instrumentos_Academias_AcademiaId" FOREIGN KEY ("AcademiaId") REFERENCES "Academias" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Evaluaciones" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProcesoId" integer NOT NULL,
    "AcademiaId" integer NOT NULL,
    "AlumnoMatricula" text NOT NULL,
    "ProfesorMatricula" text NOT NULL,
    "Grupo" text NOT NULL,
    "Materia" text NOT NULL,
    "Fecha" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Evaluaciones" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Evaluaciones_Academias_AcademiaId" FOREIGN KEY ("AcademiaId") REFERENCES "Academias" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Evaluaciones_Procesos_ProcesoId" FOREIGN KEY ("ProcesoId") REFERENCES "Procesos" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Categorias" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "InstrumentoId" integer NOT NULL,
    "Orden" integer NOT NULL,
    CONSTRAINT "PK_Categorias" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Categorias_Instrumentos_InstrumentoId" FOREIGN KEY ("InstrumentoId") REFERENCES "Instrumentos" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Comentarios" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EvaluacionId" integer NOT NULL,
    "Texto" text NOT NULL,
    CONSTRAINT "PK_Comentarios" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Comentarios_Evaluaciones_EvaluacionId" FOREIGN KEY ("EvaluacionId") REFERENCES "Evaluaciones" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Preguntas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Texto" text NOT NULL,
    "CategoriaId" integer NOT NULL,
    "Tipo" text NOT NULL,
    "Orden" integer NOT NULL,
    CONSTRAINT "PK_Preguntas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Preguntas_Categorias_CategoriaId" FOREIGN KEY ("CategoriaId") REFERENCES "Categorias" ("Id") ON DELETE CASCADE
);

CREATE TABLE "OpcionesRespuesta" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PreguntaId" integer NOT NULL,
    "Valor" integer NOT NULL,
    "Texto" text NOT NULL,
    CONSTRAINT "PK_OpcionesRespuesta" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OpcionesRespuesta_Preguntas_PreguntaId" FOREIGN KEY ("PreguntaId") REFERENCES "Preguntas" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Respuestas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EvaluacionId" integer NOT NULL,
    "PreguntaId" integer NOT NULL,
    "Valor" integer NOT NULL,
    CONSTRAINT "PK_Respuestas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Respuestas_Evaluaciones_EvaluacionId" FOREIGN KEY ("EvaluacionId") REFERENCES "Evaluaciones" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Respuestas_Preguntas_PreguntaId" FOREIGN KEY ("PreguntaId") REFERENCES "Preguntas" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Categorias_InstrumentoId" ON "Categorias" ("InstrumentoId");

CREATE UNIQUE INDEX "IX_Comentarios_EvaluacionId" ON "Comentarios" ("EvaluacionId");

CREATE INDEX "IX_Evaluaciones_AcademiaId" ON "Evaluaciones" ("AcademiaId");

CREATE INDEX "IX_Evaluaciones_ProcesoId" ON "Evaluaciones" ("ProcesoId");

CREATE INDEX "IX_Instrumentos_AcademiaId" ON "Instrumentos" ("AcademiaId");

CREATE INDEX "IX_OpcionesRespuesta_PreguntaId" ON "OpcionesRespuesta" ("PreguntaId");

CREATE INDEX "IX_Preguntas_CategoriaId" ON "Preguntas" ("CategoriaId");

CREATE INDEX "IX_Respuestas_EvaluacionId" ON "Respuestas" ("EvaluacionId");

CREATE INDEX "IX_Respuestas_PreguntaId" ON "Respuestas" ("PreguntaId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260310182416_InitialCreate', '8.0.24');

COMMIT;

START TRANSACTION;

ALTER TABLE "Evaluaciones" DROP CONSTRAINT "FK_Evaluaciones_Academias_AcademiaId";

ALTER TABLE "Evaluaciones" DROP CONSTRAINT "FK_Evaluaciones_Procesos_ProcesoId";

ALTER TABLE "Respuestas" DROP CONSTRAINT "FK_Respuestas_Preguntas_PreguntaId";

DROP INDEX "IX_Respuestas_PreguntaId";

DROP INDEX "IX_Evaluaciones_AcademiaId";

DROP INDEX "IX_Evaluaciones_ProcesoId";

ALTER TABLE "Evaluaciones" DROP COLUMN "AcademiaId";

ALTER TABLE "Evaluaciones" DROP COLUMN "AlumnoMatricula";

ALTER TABLE "Respuestas" RENAME COLUMN "Valor" TO "OpcionId";

ALTER TABLE "Evaluaciones" RENAME COLUMN "ProfesorMatricula" TO "MatriculaAlumno";

ALTER TABLE "Evaluaciones" RENAME COLUMN "Materia" TO "MateriaId";

ALTER TABLE "Evaluaciones" RENAME COLUMN "Grupo" TO "IdMaestro";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260318053114_EvaluationUpdate', '8.0.24');

COMMIT;

START TRANSACTION;


                ALTER TABLE "Procesos"
                ALTER COLUMN "Periodo" TYPE integer
                USING 
                 CASE 
                    WHEN "Periodo" = 'Septiembre - Diciembre' THEN 1
                    WHEN "Periodo" = 'Enero - Abril' THEN 2
                    WHEN "Periodo" = 'Mayo - Agosto' THEN 3
                    ELSE 0
                    END;
            

ALTER TABLE "Procesos" ADD "Nombre" text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260318180020_ProcesoFixed', '8.0.24');

COMMIT;

START TRANSACTION;

CREATE TABLE "Usuarios" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Correo" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "Rol" text NOT NULL,
    CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260320210841_userTable', '8.0.24');

COMMIT;

START TRANSACTION;

ALTER TABLE "Usuarios" RENAME COLUMN "Correo" TO "Username";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260324201023_UserUpdate', '8.0.24');

COMMIT;

START TRANSACTION;

ALTER TABLE "Instrumentos" DROP CONSTRAINT "FK_Instrumentos_Academias_AcademiaId";

DROP INDEX "IX_Instrumentos_AcademiaId";

ALTER TABLE "Instrumentos" DROP COLUMN "AcademiaId";

ALTER TABLE "Preguntas" ALTER COLUMN "Texto" TYPE character varying(500);

ALTER TABLE "OpcionesRespuesta" ALTER COLUMN "Texto" TYPE character varying(300);

ALTER TABLE "Instrumentos" ALTER COLUMN "Nombre" TYPE character varying(200);

ALTER TABLE "Instrumentos" ADD "EsPlantilla" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Instrumentos" ADD "ProcesoId" integer;

ALTER TABLE "Instrumentos" ADD "TipoInstrumento" text NOT NULL DEFAULT '';

ALTER TABLE "Categorias" ALTER COLUMN "Nombre" TYPE character varying(200);

CREATE INDEX "IX_Respuestas_PreguntaId" ON "Respuestas" ("PreguntaId");

CREATE INDEX "IX_Instrumentos_ProcesoId" ON "Instrumentos" ("ProcesoId");

ALTER TABLE "Instrumentos" ADD CONSTRAINT "FK_Instrumentos_Procesos_ProcesoId" FOREIGN KEY ("ProcesoId") REFERENCES "Procesos" ("Id") ON DELETE SET NULL;

ALTER TABLE "Respuestas" ADD CONSTRAINT "FK_Respuestas_Preguntas_PreguntaId" FOREIGN KEY ("PreguntaId") REFERENCES "Preguntas" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260412010924_instrumentUpdate', '8.0.24');

COMMIT;

START TRANSACTION;

ALTER TABLE "Instrumentos" DROP CONSTRAINT "FK_Instrumentos_Procesos_ProcesoId";

DROP INDEX "IX_Instrumentos_ProcesoId";

ALTER TABLE "Instrumentos" DROP COLUMN "ProcesoId";

ALTER TABLE "Procesos" ALTER COLUMN "Nombre" TYPE character varying(200);

ALTER TABLE "Procesos" ADD "InstrumentoId" integer;

CREATE INDEX "IX_Procesos_InstrumentoId" ON "Procesos" ("InstrumentoId");

ALTER TABLE "Procesos" ADD CONSTRAINT "FK_Procesos_Instrumentos_InstrumentoId" FOREIGN KEY ("InstrumentoId") REFERENCES "Instrumentos" ("Id") ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260412053955_instrumetToProcess', '8.0.24');

COMMIT;

START TRANSACTION;

ALTER TABLE "Procesos" ALTER COLUMN "FechaInicio" TYPE date;

ALTER TABLE "Procesos" ALTER COLUMN "FechaFin" TYPE date;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260413023628_dateOnlyUpdate', '8.0.24');

COMMIT;

START TRANSACTION;

ALTER TABLE "Evaluaciones" ADD "Grupo" text NOT NULL DEFAULT '';

ALTER TABLE "Evaluaciones" ADD "NombreMaestro" text NOT NULL DEFAULT '';

ALTER TABLE "Evaluaciones" ADD "NombreMateria" text NOT NULL DEFAULT '';

CREATE INDEX "IX_Respuestas_OpcionId" ON "Respuestas" ("OpcionId");

CREATE INDEX "IX_Evaluaciones_ProcesoId" ON "Evaluaciones" ("ProcesoId");

ALTER TABLE "Evaluaciones" ADD CONSTRAINT "FK_Evaluaciones_Procesos_ProcesoId" FOREIGN KEY ("ProcesoId") REFERENCES "Procesos" ("Id") ON DELETE CASCADE;

ALTER TABLE "Respuestas" ADD CONSTRAINT "FK_Respuestas_OpcionesRespuesta_OpcionId" FOREIGN KEY ("OpcionId") REFERENCES "OpcionesRespuesta" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260416001322_AgregarCamposDesnormalizadosEvaluacion', '8.0.24');

COMMIT;

START TRANSACTION;

ALTER TABLE "Evaluaciones" DROP CONSTRAINT "FK_Evaluaciones_Procesos_ProcesoId";

ALTER TABLE "Respuestas" DROP CONSTRAINT "FK_Respuestas_OpcionesRespuesta_OpcionId";

ALTER TABLE "Respuestas" DROP CONSTRAINT "FK_Respuestas_Preguntas_PreguntaId";

DROP INDEX "IX_Evaluaciones_ProcesoId";

ALTER TABLE "Evaluaciones" ALTER COLUMN "NombreMateria" TYPE character varying(200);

ALTER TABLE "Evaluaciones" ALTER COLUMN "NombreMaestro" TYPE character varying(200);

ALTER TABLE "Evaluaciones" ALTER COLUMN "MatriculaAlumno" TYPE character varying(20);

ALTER TABLE "Evaluaciones" ALTER COLUMN "MateriaId" TYPE character varying(20);

ALTER TABLE "Evaluaciones" ALTER COLUMN "IdMaestro" TYPE character varying(20);

ALTER TABLE "Evaluaciones" ALTER COLUMN "Grupo" TYPE character varying(20);

CREATE UNIQUE INDEX "IX_Evaluaciones_ProcesoId_MatriculaAlumno_IdMaestro_MateriaId" ON "Evaluaciones" ("ProcesoId", "MatriculaAlumno", "IdMaestro", "MateriaId");

ALTER TABLE "Evaluaciones" ADD CONSTRAINT "FK_Evaluaciones_Procesos_ProcesoId" FOREIGN KEY ("ProcesoId") REFERENCES "Procesos" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Respuestas" ADD CONSTRAINT "FK_Respuestas_OpcionesRespuesta_OpcionId" FOREIGN KEY ("OpcionId") REFERENCES "OpcionesRespuesta" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Respuestas" ADD CONSTRAINT "FK_Respuestas_Preguntas_PreguntaId" FOREIGN KEY ("PreguntaId") REFERENCES "Preguntas" ("Id") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260419000919_EvaluacionUpdate', '8.0.24');

COMMIT;

START TRANSACTION;

ALTER TABLE "Usuarios" ALTER COLUMN "Username" TYPE character varying(100);

ALTER TABLE "Usuarios" ALTER COLUMN "Rol" TYPE character varying(30);

ALTER TABLE "Usuarios" ADD "Activo" boolean NOT NULL DEFAULT TRUE;

ALTER TABLE "Usuarios" ADD "FechaActualizacion" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP);

ALTER TABLE "Usuarios" ADD "FechaCreacion" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP);

ALTER TABLE "Usuarios" ADD "PuedeGestionarInstrumentos" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Usuarios" ADD "PuedeGestionarProcesos" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Usuarios" ADD "PuedeGestionarUsuarios" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Usuarios" ADD "PuedeVerReportes" boolean NOT NULL DEFAULT FALSE;

UPDATE "Usuarios"
SET
    "Activo" = TRUE,
    "FechaCreacion" = CURRENT_TIMESTAMP,
    "FechaActualizacion" = CURRENT_TIMESTAMP,
    "PuedeGestionarUsuarios" = CASE WHEN "Rol" = 'Admin' THEN TRUE ELSE FALSE END,
    "PuedeGestionarInstrumentos" = CASE WHEN "Rol" = 'Admin' THEN TRUE ELSE FALSE END,
    "PuedeGestionarProcesos" = CASE WHEN "Rol" = 'Admin' THEN TRUE ELSE FALSE END,
    "PuedeVerReportes" = CASE WHEN "Rol" = 'Admin' THEN TRUE ELSE FALSE END;

CREATE UNIQUE INDEX "IX_Usuarios_Username" ON "Usuarios" ("Username");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260421225614_UsuariosPermisosAuditoria', '8.0.24');

COMMIT;

