CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310182416_InitialCreate') THEN
    CREATE TABLE "Academias" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" text NOT NULL,
        CONSTRAINT "PK_Academias" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310182416_InitialCreate') THEN
    CREATE TABLE "Procesos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Anio" integer NOT NULL,
        "Periodo" text NOT NULL,
        "FechaInicio" timestamp with time zone NOT NULL,
        "FechaFin" timestamp with time zone NOT NULL,
        "Activo" boolean NOT NULL,
        CONSTRAINT "PK_Procesos" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310182416_InitialCreate') THEN
    CREATE TABLE "Instrumentos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" text NOT NULL,
        "AcademiaId" integer NOT NULL,
        "Activo" boolean NOT NULL,
        CONSTRAINT "PK_Instrumentos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Instrumentos_Academias_AcademiaId" FOREIGN KEY ("AcademiaId") REFERENCES "Academias" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310182416_InitialCreate') THEN
    CREATE TABLE "Evaluaciones" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ProcesoId" integer NOT NULL,
        "AcademiaId" integer NOT NULL,
        "AlumnoMatricula" text NOT NULL,
        "ProfesorMatricula" text NOT NULL,
        "Grupo" text NOT NULL,
        "Materia" text NOT NULL,
        "Fecha" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Evaluaciones" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Evaluaciones_Academias_AcademiaId" FOREIGN KEY ("AcademiaId") REFERENCES "Academias" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Evaluaciones_Procesos_ProcesoId" FOREIGN KEY ("ProcesoId") REFERENCES "Procesos" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310182416_InitialCreate') THEN
    CREATE TABLE "Categorias" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" text NOT NULL,
        "InstrumentoId" integer NOT NULL,
        "Orden" integer NOT NULL,
        CONSTRAINT "PK_Categorias" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Categorias_Instrumentos_InstrumentoId" FOREIGN KEY ("InstrumentoId") REFERENCES "Instrumentos" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310182416_InitialCreate') THEN
    CREATE TABLE "Comentarios" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "EvaluacionId" integer NOT NULL,
        "Texto" text NOT NULL,
        CONSTRAINT "PK_Comentarios" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Comentarios_Evaluaciones_EvaluacionId" FOREIGN KEY ("EvaluacionId") REFERENCES "Evaluaciones" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310182416_InitialCreate') THEN
    CREATE TABLE "Preguntas" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Texto" text NOT NULL,
        "CategoriaId" integer NOT NULL,
        "Tipo" text NOT NULL,
        "Orden" integer NOT NULL,
        CONSTRAINT "PK_Preguntas" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Preguntas_Categorias_CategoriaId" FOREIGN KEY ("CategoriaId") REFERENCES "Categorias" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310182416_InitialCreate') THEN
    CREATE TABLE "OpcionesRespuesta" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PreguntaId" integer NOT NULL,
        "Valor" integer NOT NULL,
        "Texto" text NOT NULL,
        CONSTRAINT "PK_OpcionesRespuesta" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_OpcionesRespuesta_Preguntas_PreguntaId" FOREIGN KEY ("PreguntaId") REFERENCES "Preguntas" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310182416_InitialCreate') THEN
    CREATE TABLE "Respuestas" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "EvaluacionId" integer NOT NULL,
        "PreguntaId" integer NOT NULL,
        "Valor" integer NOT NULL,
        CONSTRAINT "PK_Respuestas" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Respuestas_Evaluaciones_EvaluacionId" FOREIGN KEY ("EvaluacionId") REFERENCES "Evaluaciones" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Respuestas_Preguntas_PreguntaId" FOREIGN KEY ("PreguntaId") REFERENCES "Preguntas" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310182416_InitialCreate') THEN
    CREATE INDEX "IX_Categorias_InstrumentoId" ON "Categorias" ("InstrumentoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310182416_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Comentarios_EvaluacionId" ON "Comentarios" ("EvaluacionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310182416_InitialCreate') THEN
    CREATE INDEX "IX_Evaluaciones_AcademiaId" ON "Evaluaciones" ("AcademiaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310182416_InitialCreate') THEN
    CREATE INDEX "IX_Evaluaciones_ProcesoId" ON "Evaluaciones" ("ProcesoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310182416_InitialCreate') THEN
    CREATE INDEX "IX_Instrumentos_AcademiaId" ON "Instrumentos" ("AcademiaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310182416_InitialCreate') THEN
    CREATE INDEX "IX_OpcionesRespuesta_PreguntaId" ON "OpcionesRespuesta" ("PreguntaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310182416_InitialCreate') THEN
    CREATE INDEX "IX_Preguntas_CategoriaId" ON "Preguntas" ("CategoriaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310182416_InitialCreate') THEN
    CREATE INDEX "IX_Respuestas_EvaluacionId" ON "Respuestas" ("EvaluacionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310182416_InitialCreate') THEN
    CREATE INDEX "IX_Respuestas_PreguntaId" ON "Respuestas" ("PreguntaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310182416_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260310182416_InitialCreate', '8.0.24');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260318053114_EvaluationUpdate') THEN
    ALTER TABLE "Evaluaciones" DROP CONSTRAINT "FK_Evaluaciones_Academias_AcademiaId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260318053114_EvaluationUpdate') THEN
    ALTER TABLE "Evaluaciones" DROP CONSTRAINT "FK_Evaluaciones_Procesos_ProcesoId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260318053114_EvaluationUpdate') THEN
    ALTER TABLE "Respuestas" DROP CONSTRAINT "FK_Respuestas_Preguntas_PreguntaId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260318053114_EvaluationUpdate') THEN
    DROP INDEX "IX_Respuestas_PreguntaId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260318053114_EvaluationUpdate') THEN
    DROP INDEX "IX_Evaluaciones_AcademiaId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260318053114_EvaluationUpdate') THEN
    DROP INDEX "IX_Evaluaciones_ProcesoId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260318053114_EvaluationUpdate') THEN
    ALTER TABLE "Evaluaciones" DROP COLUMN "AcademiaId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260318053114_EvaluationUpdate') THEN
    ALTER TABLE "Evaluaciones" DROP COLUMN "AlumnoMatricula";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260318053114_EvaluationUpdate') THEN
    ALTER TABLE "Respuestas" RENAME COLUMN "Valor" TO "OpcionId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260318053114_EvaluationUpdate') THEN
    ALTER TABLE "Evaluaciones" RENAME COLUMN "ProfesorMatricula" TO "MatriculaAlumno";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260318053114_EvaluationUpdate') THEN
    ALTER TABLE "Evaluaciones" RENAME COLUMN "Materia" TO "MateriaId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260318053114_EvaluationUpdate') THEN
    ALTER TABLE "Evaluaciones" RENAME COLUMN "Grupo" TO "IdMaestro";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260318053114_EvaluationUpdate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260318053114_EvaluationUpdate', '8.0.24');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260318180020_ProcesoFixed') THEN

                    ALTER TABLE "Procesos"
                    ALTER COLUMN "Periodo" TYPE integer
                    USING 
                     CASE 
                        WHEN "Periodo" = 'Septiembre - Diciembre' THEN 1
                        WHEN "Periodo" = 'Enero - Abril' THEN 2
                        WHEN "Periodo" = 'Mayo - Agosto' THEN 3
                        ELSE 0
                        END;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260318180020_ProcesoFixed') THEN
    ALTER TABLE "Procesos" ADD "Nombre" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260318180020_ProcesoFixed') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260318180020_ProcesoFixed', '8.0.24');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260320210841_userTable') THEN
    CREATE TABLE "Usuarios" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Correo" text NOT NULL,
        "PasswordHash" text NOT NULL,
        "Rol" text NOT NULL,
        CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260320210841_userTable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260320210841_userTable', '8.0.24');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260324201023_UserUpdate') THEN
    ALTER TABLE "Usuarios" RENAME COLUMN "Correo" TO "Username";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260324201023_UserUpdate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260324201023_UserUpdate', '8.0.24');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412010924_instrumentUpdate') THEN
    ALTER TABLE "Instrumentos" DROP CONSTRAINT "FK_Instrumentos_Academias_AcademiaId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412010924_instrumentUpdate') THEN
    DROP INDEX "IX_Instrumentos_AcademiaId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412010924_instrumentUpdate') THEN
    ALTER TABLE "Instrumentos" DROP COLUMN "AcademiaId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412010924_instrumentUpdate') THEN
    ALTER TABLE "Preguntas" ALTER COLUMN "Texto" TYPE character varying(500);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412010924_instrumentUpdate') THEN
    ALTER TABLE "OpcionesRespuesta" ALTER COLUMN "Texto" TYPE character varying(300);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412010924_instrumentUpdate') THEN
    ALTER TABLE "Instrumentos" ALTER COLUMN "Nombre" TYPE character varying(200);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412010924_instrumentUpdate') THEN
    ALTER TABLE "Instrumentos" ADD "EsPlantilla" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412010924_instrumentUpdate') THEN
    ALTER TABLE "Instrumentos" ADD "ProcesoId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412010924_instrumentUpdate') THEN
    ALTER TABLE "Instrumentos" ADD "TipoInstrumento" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412010924_instrumentUpdate') THEN
    ALTER TABLE "Categorias" ALTER COLUMN "Nombre" TYPE character varying(200);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412010924_instrumentUpdate') THEN
    CREATE INDEX "IX_Respuestas_PreguntaId" ON "Respuestas" ("PreguntaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412010924_instrumentUpdate') THEN
    CREATE INDEX "IX_Instrumentos_ProcesoId" ON "Instrumentos" ("ProcesoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412010924_instrumentUpdate') THEN
    ALTER TABLE "Instrumentos" ADD CONSTRAINT "FK_Instrumentos_Procesos_ProcesoId" FOREIGN KEY ("ProcesoId") REFERENCES "Procesos" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412010924_instrumentUpdate') THEN
    ALTER TABLE "Respuestas" ADD CONSTRAINT "FK_Respuestas_Preguntas_PreguntaId" FOREIGN KEY ("PreguntaId") REFERENCES "Preguntas" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412010924_instrumentUpdate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260412010924_instrumentUpdate', '8.0.24');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412053955_instrumetToProcess') THEN
    ALTER TABLE "Instrumentos" DROP CONSTRAINT "FK_Instrumentos_Procesos_ProcesoId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412053955_instrumetToProcess') THEN
    DROP INDEX "IX_Instrumentos_ProcesoId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412053955_instrumetToProcess') THEN
    ALTER TABLE "Instrumentos" DROP COLUMN "ProcesoId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412053955_instrumetToProcess') THEN
    ALTER TABLE "Procesos" ALTER COLUMN "Nombre" TYPE character varying(200);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412053955_instrumetToProcess') THEN
    ALTER TABLE "Procesos" ADD "InstrumentoId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412053955_instrumetToProcess') THEN
    CREATE INDEX "IX_Procesos_InstrumentoId" ON "Procesos" ("InstrumentoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412053955_instrumetToProcess') THEN
    ALTER TABLE "Procesos" ADD CONSTRAINT "FK_Procesos_Instrumentos_InstrumentoId" FOREIGN KEY ("InstrumentoId") REFERENCES "Instrumentos" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412053955_instrumetToProcess') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260412053955_instrumetToProcess', '8.0.24');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413023628_dateOnlyUpdate') THEN
    ALTER TABLE "Procesos" ALTER COLUMN "FechaInicio" TYPE date;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413023628_dateOnlyUpdate') THEN
    ALTER TABLE "Procesos" ALTER COLUMN "FechaFin" TYPE date;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413023628_dateOnlyUpdate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260413023628_dateOnlyUpdate', '8.0.24');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416001322_AgregarCamposDesnormalizadosEvaluacion') THEN
    ALTER TABLE "Evaluaciones" ADD "Grupo" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416001322_AgregarCamposDesnormalizadosEvaluacion') THEN
    ALTER TABLE "Evaluaciones" ADD "NombreMaestro" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416001322_AgregarCamposDesnormalizadosEvaluacion') THEN
    ALTER TABLE "Evaluaciones" ADD "NombreMateria" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416001322_AgregarCamposDesnormalizadosEvaluacion') THEN
    CREATE INDEX "IX_Respuestas_OpcionId" ON "Respuestas" ("OpcionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416001322_AgregarCamposDesnormalizadosEvaluacion') THEN
    CREATE INDEX "IX_Evaluaciones_ProcesoId" ON "Evaluaciones" ("ProcesoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416001322_AgregarCamposDesnormalizadosEvaluacion') THEN
    ALTER TABLE "Evaluaciones" ADD CONSTRAINT "FK_Evaluaciones_Procesos_ProcesoId" FOREIGN KEY ("ProcesoId") REFERENCES "Procesos" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416001322_AgregarCamposDesnormalizadosEvaluacion') THEN
    ALTER TABLE "Respuestas" ADD CONSTRAINT "FK_Respuestas_OpcionesRespuesta_OpcionId" FOREIGN KEY ("OpcionId") REFERENCES "OpcionesRespuesta" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416001322_AgregarCamposDesnormalizadosEvaluacion') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260416001322_AgregarCamposDesnormalizadosEvaluacion', '8.0.24');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419000919_EvaluacionUpdate') THEN
    ALTER TABLE "Evaluaciones" DROP CONSTRAINT "FK_Evaluaciones_Procesos_ProcesoId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419000919_EvaluacionUpdate') THEN
    ALTER TABLE "Respuestas" DROP CONSTRAINT "FK_Respuestas_OpcionesRespuesta_OpcionId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419000919_EvaluacionUpdate') THEN
    ALTER TABLE "Respuestas" DROP CONSTRAINT "FK_Respuestas_Preguntas_PreguntaId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419000919_EvaluacionUpdate') THEN
    DROP INDEX "IX_Evaluaciones_ProcesoId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419000919_EvaluacionUpdate') THEN
    ALTER TABLE "Evaluaciones" ALTER COLUMN "NombreMateria" TYPE character varying(200);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419000919_EvaluacionUpdate') THEN
    ALTER TABLE "Evaluaciones" ALTER COLUMN "NombreMaestro" TYPE character varying(200);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419000919_EvaluacionUpdate') THEN
    ALTER TABLE "Evaluaciones" ALTER COLUMN "MatriculaAlumno" TYPE character varying(20);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419000919_EvaluacionUpdate') THEN
    ALTER TABLE "Evaluaciones" ALTER COLUMN "MateriaId" TYPE character varying(20);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419000919_EvaluacionUpdate') THEN
    ALTER TABLE "Evaluaciones" ALTER COLUMN "IdMaestro" TYPE character varying(20);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419000919_EvaluacionUpdate') THEN
    ALTER TABLE "Evaluaciones" ALTER COLUMN "Grupo" TYPE character varying(20);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419000919_EvaluacionUpdate') THEN
    CREATE UNIQUE INDEX "IX_Evaluaciones_ProcesoId_MatriculaAlumno_IdMaestro_MateriaId" ON "Evaluaciones" ("ProcesoId", "MatriculaAlumno", "IdMaestro", "MateriaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419000919_EvaluacionUpdate') THEN
    ALTER TABLE "Evaluaciones" ADD CONSTRAINT "FK_Evaluaciones_Procesos_ProcesoId" FOREIGN KEY ("ProcesoId") REFERENCES "Procesos" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419000919_EvaluacionUpdate') THEN
    ALTER TABLE "Respuestas" ADD CONSTRAINT "FK_Respuestas_OpcionesRespuesta_OpcionId" FOREIGN KEY ("OpcionId") REFERENCES "OpcionesRespuesta" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419000919_EvaluacionUpdate') THEN
    ALTER TABLE "Respuestas" ADD CONSTRAINT "FK_Respuestas_Preguntas_PreguntaId" FOREIGN KEY ("PreguntaId") REFERENCES "Preguntas" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419000919_EvaluacionUpdate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260419000919_EvaluacionUpdate', '8.0.24');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421225614_UsuariosPermisosAuditoria') THEN
    ALTER TABLE "Usuarios" ALTER COLUMN "Username" TYPE character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421225614_UsuariosPermisosAuditoria') THEN
    ALTER TABLE "Usuarios" ALTER COLUMN "Rol" TYPE character varying(30);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421225614_UsuariosPermisosAuditoria') THEN
    ALTER TABLE "Usuarios" ADD "Activo" boolean NOT NULL DEFAULT TRUE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421225614_UsuariosPermisosAuditoria') THEN
    ALTER TABLE "Usuarios" ADD "FechaActualizacion" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421225614_UsuariosPermisosAuditoria') THEN
    ALTER TABLE "Usuarios" ADD "FechaCreacion" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421225614_UsuariosPermisosAuditoria') THEN
    ALTER TABLE "Usuarios" ADD "PuedeGestionarInstrumentos" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421225614_UsuariosPermisosAuditoria') THEN
    ALTER TABLE "Usuarios" ADD "PuedeGestionarProcesos" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421225614_UsuariosPermisosAuditoria') THEN
    ALTER TABLE "Usuarios" ADD "PuedeGestionarUsuarios" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421225614_UsuariosPermisosAuditoria') THEN
    ALTER TABLE "Usuarios" ADD "PuedeVerReportes" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421225614_UsuariosPermisosAuditoria') THEN
    UPDATE "Usuarios"
    SET
        "Activo" = TRUE,
        "FechaCreacion" = CURRENT_TIMESTAMP,
        "FechaActualizacion" = CURRENT_TIMESTAMP,
        "PuedeGestionarUsuarios" = CASE WHEN "Rol" = 'Admin' THEN TRUE ELSE FALSE END,
        "PuedeGestionarInstrumentos" = CASE WHEN "Rol" = 'Admin' THEN TRUE ELSE FALSE END,
        "PuedeGestionarProcesos" = CASE WHEN "Rol" = 'Admin' THEN TRUE ELSE FALSE END,
        "PuedeVerReportes" = CASE WHEN "Rol" = 'Admin' THEN TRUE ELSE FALSE END;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421225614_UsuariosPermisosAuditoria') THEN
    CREATE UNIQUE INDEX "IX_Usuarios_Username" ON "Usuarios" ("Username");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421225614_UsuariosPermisosAuditoria') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260421225614_UsuariosPermisosAuditoria', '8.0.24');
    END IF;
END $EF$;
COMMIT;

