// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using saed.api.Data;

#nullable disable

namespace saed.api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416001322_AgregarCamposDesnormalizadosEvaluacion")]
    partial class AgregarCamposDesnormalizadosEvaluacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("saed.api.Model.Academia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Academias");
                });

            modelBuilder.Entity("saed.api.Model.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InstrumentoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentoId");

                    b.ToTable("Categorias", (string)null);
                });

            modelBuilder.Entity("saed.api.Model.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EvaluacionId")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EvaluacionId")
                        .IsUnique();

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("saed.api.Model.Evaluacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdMaestro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MateriaId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MatriculaAlumno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreMaestro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreMateria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProcesoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcesoId");

                    b.ToTable("Evaluaciones");
                });

            modelBuilder.Entity("saed.api.Model.Instrumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsPlantilla")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TipoInstrumento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Instrumentos", (string)null);
                });

            modelBuilder.Entity("saed.api.Model.OpcionRespuesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PreguntaId")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Valor")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PreguntaId");

                    b.ToTable("OpcionesRespuesta", (string)null);
                });

            modelBuilder.Entity("saed.api.Model.Pregunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Preguntas", (string)null);
                });

            modelBuilder.Entity("saed.api.Model.Proceso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<int?>("InstrumentoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Periodo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentoId");

                    b.ToTable("Procesos", (string)null);
                });

            modelBuilder.Entity("saed.api.Model.Respuesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EvaluacionId")
                        .HasColumnType("integer");

                    b.Property<int>("OpcionId")
                        .HasColumnType("integer");

                    b.Property<int>("PreguntaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EvaluacionId");

                    b.HasIndex("OpcionId");

                    b.HasIndex("PreguntaId");

                    b.ToTable("Respuestas");
                });

            modelBuilder.Entity("saed.api.Model.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("saed.api.Model.Categoria", b =>
                {
                    b.HasOne("saed.api.Model.Instrumento", "Instrumento")
                        .WithMany("Categorias")
                        .HasForeignKey("InstrumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrumento");
                });

            modelBuilder.Entity("saed.api.Model.Comentario", b =>
                {
                    b.HasOne("saed.api.Model.Evaluacion", "Evaluacion")
                        .WithOne("Comentario")
                        .HasForeignKey("saed.api.Model.Comentario", "EvaluacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluacion");
                });

            modelBuilder.Entity("saed.api.Model.Evaluacion", b =>
                {
                    b.HasOne("saed.api.Model.Proceso", "Proceso")
                        .WithMany()
                        .HasForeignKey("ProcesoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proceso");
                });

            modelBuilder.Entity("saed.api.Model.OpcionRespuesta", b =>
                {
                    b.HasOne("saed.api.Model.Pregunta", "Pregunta")
                        .WithMany("Opciones")
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pregunta");
                });

            modelBuilder.Entity("saed.api.Model.Pregunta", b =>
                {
                    b.HasOne("saed.api.Model.Categoria", "Categoria")
                        .WithMany("Preguntas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("saed.api.Model.Proceso", b =>
                {
                    b.HasOne("saed.api.Model.Instrumento", "Instrumento")
                        .WithMany()
                        .HasForeignKey("InstrumentoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Instrumento");
                });

            modelBuilder.Entity("saed.api.Model.Respuesta", b =>
                {
                    b.HasOne("saed.api.Model.Evaluacion", "Evaluacion")
                        .WithMany("Respuestas")
                        .HasForeignKey("EvaluacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("saed.api.Model.OpcionRespuesta", "Opcion")
                        .WithMany()
                        .HasForeignKey("OpcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("saed.api.Model.Pregunta", "Pregunta")
                        .WithMany()
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluacion");

                    b.Navigation("Opcion");

                    b.Navigation("Pregunta");
                });

            modelBuilder.Entity("saed.api.Model.Categoria", b =>
                {
                    b.Navigation("Preguntas");
                });

            modelBuilder.Entity("saed.api.Model.Evaluacion", b =>
                {
                    b.Navigation("Comentario");

                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("saed.api.Model.Instrumento", b =>
                {
                    b.Navigation("Categorias");
                });

            modelBuilder.Entity("saed.api.Model.Pregunta", b =>
                {
                    b.Navigation("Opciones");
                });
#pragma warning restore 612, 618
        }
    }
}
